### ISSUE TITLE
delete를 해도 남아있는 todo의 index가 남는 현상

### ISSUE THREAD

**Issue by kyj0701** [bean3/to-do-list#38]
index가 자동 추가되는 것을 고쳐 delete하면 뒤에 있는 todo들이 index가 옮겨지도록 수정합니다.

**Comment by Alpacadabra** [comment]
index는 감소하도록 변경하였으나, id 커서가 그대로 남아있어 make시 원래 index대로 진행됩니다.
autoincrement를 수정해야 합니다.

**Comment by Alpacadabra** [comment]
해결하지 않을 예정입니다.
